# fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
      - args: [-i, --assumeFilename=.clang-format]

# repos:
# -   repo: https://github.com/bmorcos/pre-commit-hooks-cpp
#     rev: master
#     hooks:
#     -   id: clang-format
#     -   args: [-i, --assumeFilename=.clang-format]
